config/routes.rb
Rails.application.routes.draw do
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :ideas
      resources :groups  
      resources :comments        
      match 'auth/:provider/callback', to: 'session#create', via: [:get, :post]
      match 'auth/failure', to: redirect('/'), via: [:get, :post]
      match 'signout', to: 'session#destroy', as: 'signout', via: [:get, :post]
    end
  end
  get 'home/index'
  get 'home/developer' 

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :ideas #idea_id
	belongs_to :users #user_id
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :users		
end

app/models/idea.rb
class Idea < ActiveRecord::Base

	belongs_to :user #user_id
	has_many :comments, :dependent => :destroy
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :ideas
	has_many :comments
	has_and_belongs_to_many :groups
	
	def self.from_website(name,email)
		where(:email => email).first_or_initialize.tap do |user|
	      user.provider = "website"
	      user.email = email
	      user.name = name	      
	      user.save!
	    end
	end
	def self.from_omniauth(auth)		
	    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	      user.provider = auth.provider
	      user.uid = auth.uid
	      user.name = auth.info.name
	      user.email = auth.info.email
	      user.oauth_token = auth.credentials.token
	      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	      user.save!
	    end
	end
end

app/controllers/api/v1/comments_controller.rb
module Api
	module V1
		class CommentsController <  ApiController
		
			def index
				@comment = Comment.all
				render "api/comments/show"		
			end
			def show
				@comment = Comment.find(params[:id])
				render "api/comments/show"		
			end
			def create				
				@comment = Comment.new(:body => params['body'], :stars=>params['stars'], :idea_id=>params['idea_id']) 
				if @comment.save					
			        render "api/comments/create"				
				end		  		
			end

			private
				  def comment_params
				    params.require(:comment).permit(:body, :stars, :user_id)			    
				  end
			end
	end
end

app/controllers/api/v1/groups_controller.rb
module Api
	module V1
		class GroupsController <  ApiController
			def index
			  	@groups = Group.all
			  	render "api/groups/index"
			end
			def show
				@groups = Group.find(params[:id])
				render "api/groups/show"
			end

			private
			  def group_params
			    params.require(:group).permit(:name)			    
			  end
		end
	end
end

app/controllers/api/v1/ideas_controller.rb
module Api
	module V1
		class IdeasController < ApiController			
			def index
				@ideas = Idea.includes([:comments]).all.order(created_at: :desc)
				render 'api/ideas/index'
			end
			def show
				@idea = Idea.find(params[:id])
				render "api/ideas/show"
			end
			def create
				#debug.logger(params);
				#Idea.create(:idea_params) 
				@idea = Idea.new(:description => params['description'], :display=>params['display'], :user_id=>params['user_id']) 
				if @idea.save					
			        render "api/ideas/create"				
				end		  		
			end

			private
			  def idea_params
			    params.require(:idea).permit(:description, :display)			    
			  end
		end
	end
end

app/controllers/api/v1/oembed_controller.rb
module Api
	module V1
		class OembedController < ApiController
			def exercise			
				#http://localhost:3000/api/v1/oembed/poses/?url=http%3a%2f%2fwww.mypilatespal.com%2fposes%2f487
				url = params[:url]	
				
				u = URI.parse(params[:url])					
				id = u.path.split('/').last
				if(id.present?)					
						pose = Pose.find(id)
						@product = create_product_object(pose, u)
						render json: @product	
				end
			end			

			def workout
				#http://localhost:3000/api/v1/oembed/studios/?url=http%3a%2f%2fwww.mypilatespal.com%2fstudios%2f575
				url = params[:url]	
				
				u = URI.parse(params[:url])	
				host = u.host
				id = u.path.split('/').last

				if(id.present?)					
					workout = Workout.find(id, :include => [:poses])
					response = {}					
					response["provider_name"] = "#{workout.title} My Pilates Pal Workout  "
					response["url"] = url									
					products = []
					
						workout.poses.each do |pose|
					products.push(create_product_object(pose, u))			
				end
				response["products"] = products

				@response = response
				render json: @response
				#rNOT USING RABL coz it doesnt play nicely converting hash when no root is needed
				#render "api/oembed/workout"		
					
				end

			end

			private
			def create_product_object pose, u
				product = {}
				product["type"] = "link"
				product["provider_name"] = "My Pilates Pal"
				product["provider_url"]= "http://www.mypilatespal.com"
				product["version"] = "1.0"	
				tags =[]						
				tags.push("pilates", "fitness", "workout", "weight loss")						
				product["tags"] = tags
				product["author_name"] = "My Pilates Pal Instructors"
				product["author_url"] = "http://mypilatespal.com/instructors"
			 	product["price"]= 0.1
			 	product["thumbnail_url"] ="http://www.mypilatespal.com/assets/Pose1.png"
				product["thumbnail_width"] = 570
				product["thumbnail_height"] = "*"
				product["category"] = "health_fitness"
				product["availability"] = "preorder"
				product["currency_code"]="USD"	  													
				product["title"] = pose.name
				product["brand"] = "My Pilates Pal"
				product["product_id"] = pose.id 
				product["description"] = pose.description 
				product["cache_age"] = 86400
				offers =[]
                offer ={}
                offer["price"]=0.1
				offer["currency_code"]="USD"
                offers.push(offer)
				product["offers"] = offers
				images=[]
				images.push("#{u.scheme}://#{u.host}/assets/small/#{pose.image_path}")							
				product["images"] =images
				product
			end
		end		
	end
end

app/controllers/api/v1/session_controller.rb
module Api
  module V1
    class SessionController < ApiController
      #https://coderwall.com/p/bsfitw
      def create 
        auth = request.env["omniauth.auth"]
        if auth.present?
        	user = User.from_omniauth(auth)
        else
          user = User.from_website(params['name'], params['email'])
        end
        	session[:user_id] = user.id
          @session = session    
          render "api/sessions/create" 	
      end

      def destroy  	
        session[:user_id] = nil
        @session = session
        render "api/sessions/destroy" 
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
	module V1
		class UsersController < ApiController								
				
			private
			  def user_params
			    params.require(:user).permit(:name, 
			    	:email, 
			    	:location, 
			    	:provider, 
			    	:uid, 
			    	:oauth_token, 
			    	:oauth_expires_at)			    
			  end
		end
	end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController	
	respond_to :json

	def not_found(message)		 	
		log_error(message, {:priority => 1, 
							:http_status => 404, 
							:ip=>''})
		render :json => {}, :status => 404

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :set_csrf_cookie_for_ng
  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  

  protected
    def verified_request?
      super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
    end

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def loginLinks
		 unless current_user
		    link_to "Sign in with Facebook", "/api/v1/auth/facebook", id: "sign_in"
		 end
	end
end

app/views/home/developer.html.erb
<div class="well">
	<div class="content-inner">
		<h1><a href="javascript:history.back();">Idea Time Happy Hour APIs</a></h1>
		<h4>developer fun house</h4>
	</div>	
</div>
<div class="row-fluid thumbnails">
  <div class="span4">
  <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="">
      <h3>GET /Ideas</h3>
     
      <p>Get an array of idea objects</p>
       <p><%= link_to "Ideas API", api_v1_ideas_path %></p>
      <pre>{
        url: "/api/v1/ideas",
        method: "GET"
      }
      </pre>
      <p class="title">Response</p>
      <pre>
        [
        {
        "id":1,
        "description":"my great idea",
        "display":"public",
        "created_at":"2014-08-03 14:29:4 UTC",
        "hascomments":true,
        "user":{
          "name":"Joann",
          "location":"Cleveland"
        },
        "comments":[
          {"body":"jhkhk",
          "stars":5,
          "created_at":"2014-08-03 22:48:07 UTC"
        },
        {...},
        {...}
        ]}
      </pre>
    </div>
</div>
   <div class="span4">
   <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="">
      <h3>GET /Groups</h3>
      <p>Get an array of group objects</p>
       <p><%= link_to "Groups API", api_v1_groups_path %></p>
       <pre>{
        url: "/api/v1/groups",
        method: "GET"
      }
      </pre>     
      <p class="title">Response<p>
        <pre>[
          {"name":"Penquin Tea Party"},
          {"name":"Idea Time HH Board Members"}
          ]</pre>
    </div>
</div>
    <div class="span4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="">
      <h3>POST /Comment</h3>
      <p>Post comments to an idea. Pass the idea id to Comment API</p>
      <p><pre> {
      url: "/api/v1/comments",
      method: "POST",
      data: data,
      headers: {'Content-Type': 'application/json'}
    } </pre> where data is <pre>data = {
    body: "body as text", 
    stars:"stars as number", 
    idea_id: "idea id as number"
  };</pre></p>
    </div>
</div>
</div>

app/views/home/index.html.erb
<div ng-controller="IdeaController">
	<div  class="row-fluid">
		<h1 class="pump-up logo">
			<span class="strong-font">Idea Time</span>
			<span class="strong-font">Happy Hour</span>
		</h1>
		<h4 class="lead thin-font">...creative alcohol infused ideas...</h4>		  
		<form class="form-inline" name="ideaForm"> 
			<div class="alert alert-block alert-error fade in hide">	        		
				<span>Oops, you forgot to enter the idea</span>
			</div>
			<div class="input-append span12 pagination-centered">	

			  <input class="form-control input-xxlarge input-tall" ng-model="idea.description" id="ideaInput" type="text"  placeholder="What is your idea?">	
			   <% if current_user %>	
					<input type="hidden"  value="{{<%=current_user.id%>}}" id="ideaUserIdHidden"/> 
					<button type="button" role="button" class="btn btn-warning btn-large" ng-click="saveIdea(idea, ideaForm)">Submit Idea</button>
			  <% else %>			  	
				  	<a href="#loginModal" ng-click="validate(idea)" role="button" class="btn btn-large btn-warning">Enter</a>		 
			  <% end %>
			</div>   					
			<p class="small pagination-centered">

			</p>		
		</form>							
	</div>
	<div class="row-fluid">	  
	  <div class="span9">
	  	<div class="panel-heading">
		    <h3 class="panel-title thin-font">Greatest ideas</h3>
		</div>
	  	<div class="list-group">
			<div class="list-group">				
			 	<div class="list-group-item blue-bg well" ng-repeat="i in ideas | orderBy:created_at">					 		 	 
			    	<span class="badge">{{i.comments.length}}</span>			   
				    {{i.description}}	
				    <small>by {{i.user.name}}</small>			    			     
				    <div class="comments-container">				    	
					    <div ng-repeat="c in i.comments" ng-show="i.hascomments">					    	
						    <div class="panel panel-default">
							  <div class="panel-body">
							   <small>{{c.body}}</small>
							    <small class="clearfix"> on {{c.created_at | date}} </small>				   
							  </div>
							</div>								
						</div>	

					</div>						
					<form name="commentForm" novalidate ng-submit="saveComment(comment, i)" ng-controller="CommentController">
						<blockquote >
						 {{comment.body}} {{comment.stars}}
						</blockquote>
						<select ng-model="comment.stars" class="span3" ng-options="stars for stars in [5,4,3,2,1]" title="Stars">
		                  <option value="">stars</option>
		                </select>
						<input ng-model="comment.body" type="text" class="form-control" placeholder="say something about this" title="Comment"/> 						
						<input type="hidden" id="commentIdeaIdHidden" class="form-control" value="{{i.id}}" /> 						
						<button type="submit" ng-disabled="commentForm.$invalid" class="btn btn-info">Enter</button>  
					</form>					
			  </div>
			 
			</div>
		</div>	
	  </div>
	  <div class="span3">	
	  	 <h3 class="panel-title thin-font light-gray">Compete for the Oscars</h3>
	  	
	  	<img src="assets/id_oscars.png" />

	  	
	  	<!-- location -->
		<!--<div class="panel panel-danger">
		  <div class="panel-heading">
		   <h3 class="panel-title thin-font light-gray">Start an ITHH</h3>
		  </div>
		  <div class="panel-body">	    
		    <div class="form-group" >
		     <form name="locationForm" novalidate ng-submit="locationForm.$valid &&LocationCtrl.findPlace()" ng-controller="LocationController as LocationCtrl">
		     	<small>not sure yet what to do here yet</small>
		     	 <textarea class="form-control" ng-model="LocationCtrl.event.users" id="zipInput" type="text" placeholder="who to invite?"></textarea>
		     	 <p>
			    	<small class="text-info">enter email addresses - comma delimited</small>
				</p>
		     	 <input class="form-control" ng-model="LocationCtrl.event.schedule" id="zipInput" type="text" placeholder="when?">
			  <input class="form-control" ng-model="LocationCtrl.event.location.name" id="zipInput" type="text" placeholder="where?">-->
			  <!--<label class="control-label" for="zipInput">Find a place</label>
			  <input class="form-control input-mini" ng-model="LocationCtrl.location.zip" id="zipInput" type="text" placeholder="enter zip" value="44124">
			  <p>
			    I already have a location picked.

			</p>-->			
			<!--<p>			 
			  <button type="submit" class="btn btn-warning">Invite</button>			  
			</p>
			<div id="map-canvas"></div>
			</form>
			</div>				
		  </div>
		</div>-->
	  </div>
	</div>	

	<!-- Modal -->
<div id="loginModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">One more thing...</h3>
  </div>
  <div class="modal-body">  	
  	{{idea}}	
    <p>We need to know more about you so that you can:
    	<ul>
    		<li>Submit your greatest (never dumb) idea</li>
    		<li>Schedule an Idea Time Happy Hour with your possy</li>
    		
    	</ul>
    	<div id="user-widget">
		  <%= loginLinks() %>
		</div>
		<h3>OR</h3>
		<p> Enter your name &amp; email, so you're assigned the proud owner of the great idea </p>
		<form name="userForm" ng-controller="SessionController" ng-submit="userForm.$valid && signIn(user, idea)" novalidate>

			<input class="form-control" ng-model="user.name" id="nameInput" type="text" placeholder="your name, nickname, whatever you want...">
			<input class="form-control" required ng-model="user.email" id="emailInput" type="text" placeholder="your@email.com" value="test@test.com">
			<input class="form-control" ng-hide="true" ng-model="user.provider" id="providerInput" type="text" value="website">
			<span class="error" ng-show="userForm.input.$error.required">Required!</span>
			<span class="error" ng-show="userForm.input.$error.email">Not valid email!</span>
			<p class="small">If you already sign up, just enter your email. We will look you up</p>
			<button type="submit" class="btn btn-warning">Submit Idea</button>		
		</form>
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>   
  </div>
</div>  	


</div>

app/views/layouts/_footer.html.erb
<p class="well">
Copyright 2012 - All ideas in this site are of sole ownership of the author. You may not modify, publish, copy, transmit, transfer, sell, reproduce, create derivative works from, license, distribute, frame, hyperlink, download, repost, perform, display or in any way commercially exploit any of the content of this site without the permission of the author. Or Someone will find you and you will not be found again!
</p>

app/views/layouts/_header.html.erb
<div class="row-fluid">
	<div class="span9">
		<%= loginLinks() %>		
		<% if current_user %>
	 	 <span><%= "Welcome #{current_user.name}"%></span>      	              
	     <form name="userForm" ng-controller="SessionController" ng-submit="userForm.$valid && signOut()" novalidate>			
	     	<button type="submit" class="btn btn-danger">Bye Bye</button>		
		</form>
		<% end %>
	</div>
	<div class="span3"><%= link_to "For Developers", home_developer_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Idea Time Happy Hour - alcohol infused ideas!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>  
  <link rel="stylesheet" type="text/css" href="assets/libraries/bootstrap-responsive.css" />
  <!--<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Montserrat:700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= auto_discovery_link_tag :rss %> 
  <meta name="description" content="Idea time happy hour meetups where best ideas come alive">
  <meta name="keyword" content="idea, happy hour, fun, meetup ">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <link rel="apple-touch-icon" href="/appleicon.png"/>  
  <link rel="shortcut icon" href="/favicon.ico" />
   <%= yield :head %>
</head>
<body ng-app="Home" class="bg">
<div class="container">
  <div class="header"> 
    <%= yield :header %>
    <%= render 'layouts/header' %>
  </div>
  <div class="content"><%= yield %></div>
  <div class="footer">
    <%= yield :footer %>
    <%= render 'layouts/footer' %>
  </div>
</div>
</body>
</html>